---
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dependencies:
  - role: creategroup
    _name: caas_etcd
    _gid: "{{ caas.uid.caas_etcd }}"
    become: true
    become_user: "root"

  - role: createuser
    _name: caas_etcd
    _group: caas_etcd
    _groups: ''
    _shell: /sbin/nologin
    _home: /var/lib/etcd
    _uid: "{{ caas.uid.caas_etcd }}"
    become: true
    become_user: "root"

  - role: creategroup
    _name: kube
    _gid: "{{ caas.uid.kube }}"
    become: true
    become_user: "root"

  - role: createuser
    _name: kube
    _group: kube
    _groups: ''
    _shell: /sbin/nologin
    _home: /
    _uid: "{{ caas.uid.kube }}"
    become: true
    become_user: "root"

  - role: cert
    instance: "etcd{{ nodeindex }}"
    cert_path: /etc/etcd/ssl
    common_name: "etcd"
    alt_names:
      ip:
        "{{ lookup('template', 'caas-master-nodes.j2') | from_yaml }}"
    add_users:
      - caas_etcd
      - kube # needed for apiserver
    become: true
    become_user: "root"

  - role: docker_image_load
    images:
      - etcd
